### PR TITLE
[lisp/geo/geopack.l] maxindex supports (1, n) vector

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
the travis test says
```
[32mstart testing [test-hanoi-arm]
[0minconsistent face settingerr: 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by k-okada** [comment]
restarted travis, but may be you have wrong commit

--
◉ Kei Okada

**Comment by wkentaro** [comment]
You're right. I checked in my env and  the test fails because of this change.
The `maxindex` has been used as function for 3-d vector, and this change may be difficult and dangerous.

**Comment by wkentaro** [comment]
close for now.

**Pull request closed without merging**
