### PR TITLE
[euslisp/models/room610-tray-object.l] add turtlebot tray marker text…

### PR DESCRIPTION
**Pull request by furushchev**
…ure to tray object for irt 610 demo

screenshot_from_2015-07-08 22 04 44

### CODE REVIEW

**Comment by k-okada** [comment]
@snozawa  where is the instructions to how to convert model in euslib to irteus?

**Comment by furushchev** [comment]
if possible, not only converting, I'd also like to know how to edit model (e.g. add door to washing machine)

**Comment by snozawa** [comment]
Please see wiliki page (I send e-mail later).

**Comment by furushchev** [comment]
@snozawa Thank you for kind instruction. I'll do and commit later.

**Pull request closed without merging**
