### PR TITLE
[lisp/image/piximage.l] fix image color order

### PR DESCRIPTION
**Pull request by furushchev**
in euslisp pixel order of 24-bit image is assumed "RGB", not "BGR".
c.f. https://github.com/euslisp/EusLisp/blob/master/lisp/image/piximage.l#L362

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada please merge if there is no problem.

**Comment by k-okada** [comment]
> in euslisp pixel order of 24-bit image is assumed "RGB", not "BGR".

how do you know this.

**Comment by furushchev** [comment]
@k-okada Please see `c.f.` in my first comment.

**Comment by k-okada** [comment]
I see

**Comment by furushchev** [comment]
@k-okada Please merge if there is no problem.

**Pull request merged**
