### PR TITLE
[models] add eng2-7f eng2-7f-northwing eng2-7f-southwing eng2-7f-elevatorhall eng2-8f scene models

### PR DESCRIPTION
**Pull request by furushchev**
added auto generated files

[Review on Reviewable](https://reviewable.io/reviews/euslisp/euslisp/145)

### CODE REVIEW

**Comment by furushchev** [comment]
please merge if there is no problem

**Comment by k-okada** [comment]
do you think we can create one (or few) wall object files, instead of 1000 files.

**Comment by k-okada** [comment]
do we really need to change over 1000 files?

**Comment by k-okada** [comment]
closed, please re-open or submit selected files

**Pull request closed without merging**
