### PR TITLE
Add pattern option in :methods

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Adding `pattern` option to `:methods`. It is defined in `:method-names` and also used in `:all-method-names`. 

Also using `mapcan` for smaller and more efficient code. `:all-method-names` returns a new list every time, so shouldn't have any problems with side effects.

With this changes we can, for instance:
```
(setq c (make-coords))
(send c :methods :parent)
;; > (:parentcoords :parent-vector :parent-orientation)
```
Works the same for `'parent` and `"parent"`.

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Travis CI could not complete due to the following error, when testing on `osx` system.
```
shell_session_update: command not found
```

**Comment by wkentaro** [comment]
I'm not sure, and `shel_session_update` is not the function we define in `travis.sh` so maybe travis bug?

The latest success build of travis is 11 days ago.

image

**Comment by wkentaro** [comment]
I found people who encounter the same problem: https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-349587627

**Comment by Affonso-Gui** [comment]
Rebuilding

**Comment by Affonso-Gui** [comment]
Rebuild

**Comment by Affonso-Gui** [comment]
@k-okada Please review

**Comment by k-okada** [comment]
humm, if you support this future, will we want to know "method-names" vs "all-methods-names"?
```
15.E3-eusgl$ (send (class c) :method-names "val")
nil
16.E3-eusgl$ (send (class c) :all-method-names "val")
((coordinates nil) (propertied-object nil) (object (:get-val :set-val)))
```

BTW, are we missing `:methods` entry in jmanual?

**Comment by Affonso-Gui** [comment]
This feature would search substrings appearing in `all-method-names`, according to original `:methods` definition. I don't believe it is necessary to grant a way to distinguish methods defined only on the child class (like in `method-names`).

With this PR the result of the above would be:
```
(send c :methods "val")
;; > (:get-val :set-val)
```
 Which I believe it is easier to read and use than similar `(send (class c) :all-method-names "val")`.


The jmanual appears to only have entry for `(send (class c) :methods)`, but not for `(send c :methods)`.

> metaclass
:methods
このクラスで定義された全てのメソッドのリストを返す。そのリストは、メソッド名とパラメータと本体を組みにしたリストによって構成されたリストである。

**Comment by Affonso-Gui** [comment]
@k-okada please review

**Comment by Affonso-Gui** [comment]
@k-okada It appears that the documentation in jmanual only references metaclass `:methods` (i.e. `(send (class c) :methods)`, and not object instances `:methods` (i.e. `(send c :methods)`).

Should I:
1. Edit metaclass entry mentioning &optional argument in instances -- Maybe add &optional to metaclass too?
2. Add another entry for object instances
3. Add documentation string to the function, without changing jmanual

**Comment by k-okada** [comment]
how about 2 & 3

--
◉ Kei Okada


2018-04-09 18:11 GMT+09:00 Affonso, Guilherme <notifications@github.com>:

**Comment by Affonso-Gui** [comment]
@k-okada Added documentation. Please check.

**Comment by k-okada** [comment]
please update english documentation too   Commits 3   Files changed 2
￼ Changes from all commits 
￼Jump to…

**Comment by Affonso-Gui** [comment]
@k-okada ping

**Pull request merged**
