### PR TITLE
add &optional n in last

### PR DESCRIPTION
**Pull request by knorth55**
```lisp
2. irteusgl$ (last (list 1 2 3))
(3)
3. irteusgl$ (last (list 1 2 3) 0)
nil
4. irteusgl$ (last (list 1 2 3) 1)
(3)
5. irteusgl$ (last (list 1 2 3) 2)
(2 3)
6. irteusgl$ (last (list 1 2 3) 3)
(1 2 3)
7. irteusgl$ (last (list 1 2 3) 4)
(1 2 3)
```

### CODE REVIEW

**Comment by YoheiKakiuchi** [comment]
Is it very slow for large list ?

**Comment by knorth55** [comment]
@YoheiKakiuchi 
Thank you for your comment.
I tried timer testing as below.
- Current:  `0.491427[s]`
- this PR: `11.3937[s]`
I need to refine the code...

```lisp
(setq timer (instance mtimer :init))
(setq a (make-list 10000))

(send timer :start)
(dotimes (i 10000)
  (last a))
(pprint (send timer :stop))
```

**Comment by knorth55** [comment]
I updated to use `nreverse` and much faster.

  - Current: 0.491427[s]
 - this PR: 1.30573 [s]

**Comment by YoheiKakiuchi** [comment]
'nreverse' destructs given list, so current version may reverse given list

**Comment by YoheiKakiuchi** [comment]
FYI: code of sbpl
https://sourceforge.net/p/sbcl/sbcl/ci/master/tree/src/code/list.lisp#l280

**Comment by knorth55** [comment]
I change code to this and `0.7[s]`.
` (nthcdr (max (- (length x) n) 0) x))`

**Comment by Affonso-Gui** [comment]
Just for the record, I just discovered that the following holds for both sbcl and clisp.
```
> (last (cons 1 2) 0)
2
```
This kind of also explains why implementation of function `last` on sbcl separates cases when `n` is zero but do not return `nil` for all of them.

**Comment by Affonso-Gui** [comment]
@knorth55 maybe re-target this to `cl-compatible` branch?

**Pull request closed without merging**
