### PR TITLE
[lisp/l/string.l] add url encode feature

### PR DESCRIPTION
**Pull request by furushchev**
This PR adds `:encode` method to url-pathname class, which serves url percent encoding.

```lisp
1.irteusgl$ setq u (url-pathname "https://www.google.co.jp/?q=東大 ロボット")
#<url-pathname #x55a67c0 "https://www.google.co.jp:80/?q=東大 ロボット">
2.irteusgl$ send u :encode
#<url-pathname #x55a67c0 "https://www.google.co.jp:80/?q=%e6%9d%b1%e5%a4%a7+%e3%83%ad%e3%83%9c%e3%83%83%e3%83%88">
```

### CODE REVIEW

**Comment by k-okada** [comment]
please update documents

**Comment by furushchev** [comment]
@k-okada OK. added doc. travis passed

**Comment by k-okada** [comment]
lgtm, wait for other's objection

--
◉ Kei Okada

**Comment by garaemon** [comment]
* stringstream nay be better than firmat 
* is encode-url ok? I think escape is better word.

**Comment by furushchev** [comment]
@garaemon Thank you for reviewing.

> stringstream nay be better than firmat

Sorry, I could not get it. What do you mean?

> is encode-url ok? I think escape is better word.

OK. I'll rename.

**Comment by garaemon** [comment]
> stringstream nay be better than firmat

format is the correct word.
format is not good at concatenating string.

**Comment by furushchev** [comment]
@garaemon OK. I fixed. Could you re-review new commit?

**Comment by furushchev** [comment]
If re-review is ok, then I also fix the test code. euslisp/jskeus#252

**Comment by furushchev** [comment]
Well, this is ok?

**Comment by garaemon** [comment]
lgtm

**Pull request merged**
