### PR TITLE
add .gitignore

### PR DESCRIPTION
**Pull request by takayuki5168**
I think this is needed.

If unneeded, please delete this PR.

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
@takayuki5168 ping

**Comment by takayuki5168** [comment]
Thanks for your ping.

I compiled with latest master branch, then below untracked files came up.
```
Linux64/
doc/jlatex/jmanual.aux
doc/jlatex/jmanual.idx
doc/jlatex/jmanual.ilg
doc/jlatex/jmanual.ind
doc/jlatex/jmanual.log
doc/jlatex/jmanual.out
doc/jlatex/jmanual.toc
doc/latex/manual.aux
doc/latex/manual.idx
doc/latex/manual.ilg
doc/latex/manual.ind
doc/latex/manual.log
doc/latex/manual.out
doc/latex/manual.toc
include
lisp/Makefile
lisp/c/makedate.c
lisp/comp/builtins.l.c
lisp/comp/comp.c
lisp/comp/comp.h
lisp/comp/trans.c
lisp/comp/trans.h
lisp/geo/bodyrel.c
lisp/geo/bodyrel.h
lisp/geo/compose.c
lisp/geo/compose.h
lisp/geo/dda.c
lisp/geo/dda.h
lisp/geo/geobody.c
lisp/geo/geobody.h
lisp/geo/geoclasses.c
lisp/geo/geoclasses.h
lisp/geo/geopack.c
lisp/geo/geopack.h
lisp/geo/hid.c
lisp/geo/hid.h
lisp/geo/polygon.c
lisp/geo/polygon.h
lisp/geo/primt.c
lisp/geo/primt.h
lisp/geo/shadow.c
lisp/geo/shadow.h
lisp/geo/viewing.c
lisp/geo/viewing.h
lisp/geo/viewport.c
lisp/geo/viewport.h
lisp/geo/viewsurface.c
lisp/geo/viewsurface.h
lisp/image/pbmfile.c
lisp/image/pbmfile.h
lisp/image/piximage.c
lisp/image/piximage.h
lisp/l/array.c
lisp/l/array.h
lisp/l/common.c
lisp/l/common.h
lisp/l/constants.l.c
lisp/l/coordinates.c
lisp/l/coordinates.h
lisp/l/cyclic.c
lisp/l/cyclic.h
lisp/l/eusdebug.c
lisp/l/eusdebug.h
lisp/l/eusforeign.c
lisp/l/eusforeign.h
lisp/l/eushelp.c
lisp/l/eushelp.h
lisp/l/eusstart.l.c
lisp/l/extnum.c
lisp/l/extnum.h
lisp/l/hashtab.c
lisp/l/hashtab.h
lisp/l/history.c
lisp/l/history.h
lisp/l/loader.c
lisp/l/loader.h
lisp/l/mathtran.c
lisp/l/mathtran.h
lisp/l/object.c
lisp/l/object.h
lisp/l/packsym.c
lisp/l/packsym.h
lisp/l/par.c
lisp/l/par.h
lisp/l/pprint.c
lisp/l/pprint.h
lisp/l/process.c
lisp/l/process.h
lisp/l/readmacro.c
lisp/l/readmacro.h
lisp/l/stream.c
lisp/l/stream.h
lisp/l/string.c
lisp/l/string.h
lisp/l/toplevel.c
lisp/l/toplevel.h
lisp/l/tty.c
lisp/l/tty.h
lisp/opengl/src/eglforeign.c
lisp/opengl/src/eglforeign.h
lisp/opengl/src/glconst.c
lisp/opengl/src/glconst.h
lisp/opengl/src/gldecl.c
lisp/opengl/src/gldecl.h
lisp/opengl/src/gleus.c
lisp/opengl/src/gleus.h
lisp/opengl/src/glforeign.c
lisp/opengl/src/glforeign.h
lisp/opengl/src/glprim.c
lisp/opengl/src/glprim.h
lisp/opengl/src/gltexture.c
lisp/opengl/src/gltexture.h
lisp/opengl/src/gluconst.c
lisp/opengl/src/gluconst.h
lisp/opengl/src/gluforeign.c
lisp/opengl/src/gluforeign.h
lisp/opengl/src/glutil.c
lisp/opengl/src/glutil.h
lisp/opengl/src/glview.c
lisp/opengl/src/glview.h
lisp/opengl/src/glxconst.c
lisp/opengl/src/glxconst.h
lisp/opengl/src/glxforeign.c
lisp/opengl/src/glxforeign.h
lisp/opengl/src/toiv.c
lisp/opengl/src/toiv.h
lisp/xwindow/Xapplwin.c
lisp/xwindow/Xapplwin.h
lisp/xwindow/Xcanvas.c
lisp/xwindow/Xcanvas.h
lisp/xwindow/Xcolor.c
lisp/xwindow/Xcolor.h
lisp/xwindow/Xdecl.c
lisp/xwindow/Xdecl.h
lisp/xwindow/Xeus.c
lisp/xwindow/Xeus.h
lisp/xwindow/Xevent.c
lisp/xwindow/Xevent.h
lisp/xwindow/Xgraphics.c
lisp/xwindow/Xgraphics.h
lisp/xwindow/Xitem.c
lisp/xwindow/Xitem.h
lisp/xwindow/Xmenu.c
lisp/xwindow/Xmenu.h
lisp/xwindow/Xpanel.c
lisp/xwindow/Xpanel.h
lisp/xwindow/Xscroll.c
lisp/xwindow/Xscroll.h
lisp/xwindow/Xtext.c
lisp/xwindow/Xtext.h
lisp/xwindow/Xtop.c
lisp/xwindow/Xtop.h
```

Different untracked files between us are below.
```bash
$ diff t-murooka_untracked.txt gui_untracked.txt 
0a1
>     CMakeLists.txt
1a3
>     cmake/
8a11,12
>     doc/latex/TAGS
>     doc/latex/irtmodel.tex
15a20,21
>     doc/latex/test.o
>     env-hooks/
70,71d75
<     lisp/l/extnum.c
<     lisp/l/extnum.h
153a158
>     package.xml
```


I want you to compile again with latest master version.

In addition, I want to add `*.hlp`, `*.dvi` in `.gitignore`.

**Comment by Affonso-Gui** [comment]
```
CMakeLists.txt
cmake/
env-hooks/
package.xml
```
Are generated when installing together with roseus https://github.com/jsk-ros-pkg/jsk_roseus#use-roseus-with-euslisp-built-from-source, but I think it is ok to leave them out of the .gitignore, since they are not generated directly from this repository. 

Also, the directory `Linux64` is one of the many options that may be generated from the make file. Other possibilities include:
```
Darwin
Linux
IRIX
Alpha
Cygwin
LinuxARM
LinuxSH4
SunOS4
SunOS5
IRIX6
```

**Comment by takayuki5168** [comment]
Good advise.
I added those architectures in `.gitignore`.

**Comment by takayuki5168** [comment]
@k-okada Please check and merge if nothing is wrong.

**Comment by takayuki5168** [comment]
@k-okada Please merge this PR if there are no problems.

**Comment by Affonso-Gui** [comment]
@k-okada

**Comment by k-okada** [comment]
> Are generated when installing together with roseus https://github.com/jsk-ros-pkg/jsk_roseus#use-roseus-with-euslisp-built-from-source, but I think it is ok to leave them out of the .gitignore, since they are not generated directly from this repository.

what is the objective of adding `.gitignore`? If you want to keep the output of `git status` clean, then I think we should add `CMakeLists.txt`, `package.xml` ... to `.gitignore`.
How about files generated when compiling jskeus ?
```
	lib/irtext.l
	lib/llib/pgsql.c
	lib/llib/pgsql.h
	lib/llib/time.c
	lib/llib/time.h
```

**Comment by Affonso-Gui** [comment]
The main objective would be indeed to keep the git status clean (or cleaner). I do not have any strong opinions about adding or not adding roseus and jskeus compile files as well, but just for reference what would be the arguments NOT to add a gitignore?

**Comment by takayuki5168** [comment]
I don't do maintenance on this PR anymore, so I close.
If this PR should still be opened, please make another PR.

**Pull request closed without merging**
