### PR TITLE
fix: remove/delete/substitute sequence with :end :count

### PR DESCRIPTION
**Pull request by furushchev**
Closes https://github.com/euslisp/EusLisp/issues/295

Test case is https://github.com/euslisp/jskeus/pull/509

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Having problems with `:count` in `substitute` too. 
```lisp
(substitute 'b 'a #(a b a d) :count 1)
;; #(b)
```
Will send a PR shortly.

**Comment by Affonso-Gui** [comment]
https://github.com/furushchev/EusLisp/pull/1

**Comment by Affonso-Gui** [comment]
@k-okada ping

**Comment by k-okada** [comment]
can we re-target this to `cl-compatible` branch?

**Comment by Affonso-Gui** [comment]
Although `:count` problem is not a cl-compatibility issue, but rather a eus bug
```lisp
irteusgl$ (remove 1 (vector 1 2 3 2 1) :count 1)  ;; -> #()
```
`:end` key is a bit more tricky, and may indeed affect existing programs.
```lisp
irteusgl$ (delete 2 (vector 1 2 3 2 1) :end 2)     ;; -> #(1)
```
Considering so, it might indeed be a good idea to target `cl-compatible`.
@furushchev

**Comment by furushchev** [comment]
@Affonso-Gui Exactly this is a bug rather than `cl-compatibility` issue but I don't think this change does not change the existing behavior so to affect existing programs because this PR is just for making `:start`, `:end` and `:count` work.
(The result of the two commands is not changed before/after this PR).

@k-okada 
For the target branch of this PR, both are ok for me. :+1:

**Comment by k-okada** [comment]
yes but someone is already using this, let's merge into `cl-compatible` and also please use euslisp with this patch for your research demo and see if does not have any side effects
```
k-okada@p51s:~/catkin_ws/ws_euslib/src/euslib$ find -iname *.l -exec grep \(delete\  {} \; | grep :count
          (setq *process-pool* (delete target-process *process-pool* :count 1))
		   (delete tmp answer :count 1))
	(setq selected (delete (cadr selected) selected :count 1))
	(setq selected (delete (cadr selected) selected :count 1))
		(setq *vertices* (delete ip *vertices* :count 1)) )))
      (setq cand-verts (delete avert cand-verts :key #'car :count 1)))
			  (setq *vertices* (delete ver *vertices* :count 1)))
		 (setq newregion (delete (car p1) newregion :count 1))
		 (setq newregion (delete (car p2) newregion :count 1))
	       (setq regions (append newregion (delete aregion regions :count 1)))
  		     (setq *vertices* (delete cpv *vertices* :count 1))))
			   (setq *vertices* (delete ver *vertices* :count 1)))
      (setq open-list (delete min-x open-list :count 1))
	   (delete v uni :count 1))
	   (delete v uni :count 1))
	   (delete v uni :count 1))
	   (delete v uni :count 1))
```

**Comment by furushchev** [comment]
@Affonso-Gui @k-okada Changed the target branch.

**Pull request merged**
