### PR TITLE
Share uninterned symbols in *print-circle*

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Makes `(let ((g (gensym))) (list g g))` print as `(#1=#:G824 #1#)`, when \*print-circle\* is non-nil. Since this is a dumpable and loadable form, #266 gets solved. (It is also default behavior in clisp and sbcl.)

Can be tested with below code:
```
(let ((lst (let ((g (gensym))) (list g g)))
      (*print-circle* t))
  (assert
   (reduce #'eq (read-from-string (format nil "~S" lst)))
   "Unable to read uninterned symbol"))
```

### CODE REVIEW

**Comment by k-okada** [comment]
please use `restart travis euslisp/EusLisp 709.9`

--
◉ Kei Okada


2018-04-03 9:39 GMT+09:00 Affonso, Guilherme <notifications@github.com>:

**Comment by k-okada** [comment]
need to merge https://github.com/euslisp/EusLisp/pull/273

**Comment by Affonso-Gui** [comment]
@inabajsk Please review

**Comment by Affonso-Gui** [comment]
To give a better explanation of the problem:

Symbols generated by `(gensym)` cannot be correctly readen from files, creating different objects for the same symbol representation.
```
(apply #'eq (read-from-string "(#:test #:test)"))
  ;; -> nil
```
This causes problems e.g. when trying to load hash tables from dumped files, as reported on #266.

In common lisp, this problem is solved by writing files using labeled notation, when \*print-circle\* is non-nil.
```
(let* ((g (gensym))
       (lst (list g g))
       (*print-circle* t))
  (format t "~s" lst))
;; -> (#1=#:G966 #1#)

(apply #'eq (read-from-string "(#1=#:G966 #1#)"))
  ;; -> t
```

This PR takes the same approach as common lisp implementation. It can be tested with the following:
```
(let ((lst (let ((g (gensym))) (list g g)))
      (*print-circle* t))
  (assert
   (apply #'eq (read-from-string (format nil "~S" lst)))
   "Unable to read uninterned symbol"))
```

**Comment by k-okada** [comment]
can you put test code into jskeus/irteus/test ?

**Comment by Affonso-Gui** [comment]
@k-okada added in https://github.com/euslisp/jskeus/pull/501

**Comment by Affonso-Gui** [comment]
@k-okada ping

**Pull request merged**
