### PR TITLE
change trashbox0 handles' coordinates

### PR DESCRIPTION
**Pull request by mqcmd196**
To grasp room73b2-trashbox0's edges by robots on irt-viewer, I fixed handle coordinates of 'room73b2-trashbox0'.

`(setq *trashbox* (room73b2-trashbox0)) (send *trashbox* :handle :draw-on :flush t)` shows
before
Screenshot from 2020-09-15 16-31-33

after
Screenshot from 2020-09-15 17-08-43

PR2 grasps the `room73b2-trashbox0` by using new `:handle` coordinate. 
Screenshot from 2020-09-15 17-07-18

### CODE REVIEW

**Comment by knorth55** [comment]
maybe we need to update `euslib/rbrain/jskmapclass.l` and build it like below.
https://github.com/jsk-ros-pkg/euslib/pull/335
https://github.com/euslisp/EusLisp/pull/439

I'm figuring out how to do it with this trashbox, but I'm suffering build error...

**Comment by mqcmd196** [comment]
Thanks for your checking my PR.
I see. So I should edit [rbrain/jskmapclass.l](https://github.com/jsk-ros-pkg/euslib/blob/master/rbrain/jskmapclass.l) at the same time.
There are a lot of `trashbox` words in the code, and I couldn't find out where to fix...

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/euslib/blob/master/rbrain/jskmapclass.l#L8024
https://github.com/jsk-ros-pkg/euslib/blob/master/rbrain/jskmapclass.l#L8108
please overwrite :set-handle
--
◉ Kei Okada



2020年9月15日(火) 23:30 Yoshiki Obinata <notifications@github.com>:

**Comment by mqcmd196** [comment]
Thanks, I'll fix and send another PR.

**Review by knorth55 — APPROVED** [review]

**Comment by knorth55** [comment]
:sob: 

```
Done: Job Cancelled
Job has been terminated due to insufficient credits balance
```

https://app.travis-ci.com/github/euslisp/EusLisp/jobs/534980437

**Comment by mqcmd196** [comment]
omg...

**Pull request merged**
