### PR TITLE
add argument to defun

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
add argument to defun for adding documentation string to functions written by C
This is another implementation of
https://github.com/euslisp/EusLisp/pull/111

for using variable arguments we must know number of arguments.

### CODE REVIEW

**Comment by garaemon** [comment]
Is it possible to use `va_list` to keep compatibility?
http://www.cprogramming.com/tutorial/c/lesson17.html

**Comment by YoheiKakiuchi** [comment]
for using va_list we must know number of arguments.
if using defun by legacy style, va_arg may return incorrect pointer (it's not char *) from stack.
we have no way to check pointer is char * or not.

**Comment by k-okada** [comment]
wow, this is very tricky but seems to work well.
+1

**Comment by k-okada** [comment]
@YoheiKakiuchi can we merge this?

**Comment by YoheiKakiuchi** [comment]
Yes.

**Pull request merged**
