### PR TITLE
fix documentation of round function

### PR DESCRIPTION
**Pull request by otsubo**
The example result of round function may be incorrect.
 I added minus symbol.

### CODE REVIEW

**Comment by k-okada** [comment]
Thank you for contributing EusLisp documentation<br>
Please check latest documents before merging<br>

PDF version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/307/artifacts/0//home/circleci/project/artifacts/manual.pdf' target='_blank'>manual.pdf</a></strong>
PDF version of Japanese jmanual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/307/artifacts/0//home/circleci/project/artifacts/jmanual.pdf' target='_blank'>jmanual.pdf</a></strong>
HTML version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/307/artifacts/0//home/circleci/project/artifacts/html/manual.html' target='_blank'>manual.html</a></strong>
HTML version of Japanese manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/307/artifacts/0//home/circleci/project/artifacts/html/jmanual.html' target='_blank'>jmanual.html</a></strong>
Sphinx (ReST) version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/307/artifacts/0//home/circleci/project/artifacts/rst/html/manual.html' target='_blank'>manual.rst</a></strong>

**Comment by otsubo** [comment]
I have confirmed them.
It seems to be fine.

**Comment by k-okada** [comment]
Thank you for contributing EusLisp documentation<br>
Please check latest documents before merging<br>

PDF version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/341/artifacts/0//home/circleci/project/artifacts/manual.pdf' target='_blank'>manual.pdf</a></strong>
PDF version of Japanese jmanual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/341/artifacts/0//home/circleci/project/artifacts/jmanual.pdf' target='_blank'>jmanual.pdf</a></strong>
HTML version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/341/artifacts/0//home/circleci/project/artifacts/html/manual.html' target='_blank'>manual.html</a></strong>
HTML version of Japanese manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/341/artifacts/0//home/circleci/project/artifacts/html/jmanual.html' target='_blank'>jmanual.html</a></strong>
Sphinx (ReST) version of English manual: <strong><a href='https://circleci.com/gh/euslisp/EusLisp/341/artifacts/0//home/circleci/project/artifacts/rst/html/manual.html' target='_blank'>manual.rst</a></strong>

**Comment by k-okada** [comment]
I think travis is designed to upload pdf files for ever release, not every
commit. because updating PDF consumes a lot of github strage
https://github.com/euslisp/EusLisp/blob/master/.travis.yml#L120

I think if you know `--depth 1` option, it does not matter, but a lot of
people do not use euslib just because it is heavy.
c.f. https://github.com/jsk-ros-pkg/euslib/issues/216

--
◉ Kei Okada



2020年2月5日(水) 15:49 Affonso, Guilherme <notifications@github.com>:

**Comment by Affonso-Gui** [comment]
@k-okada I am just interested in the `.hlp` files updates, no need to commit the new pdf.
Actually what we really need is to run the `(make-help)` command, which has been included as the help target at the make file in https://github.com/euslisp/EusLisp/pull/359

i.e.
```
make help
```

**Pull request merged**
