### PR TITLE
fix opposite char comparison function

### PR DESCRIPTION
**Pull request by furushchev**
this fix issue #122

### CODE REVIEW

**Comment by k-okada** [comment]
please add test code

**Comment by furushchev** [comment]
where should I put test codes of euslisp... in euslisp/jskeus?

**Comment by k-okada** [comment]
https://github.com/euslisp/jskeus/blob/master/irteus/test/min-max.l

--
◉ Kei Okada

**Comment by k-okada** [comment]
or create new file, arith.l bsaic.l ...

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thank you for clear instruction. If I would create new files for test, where they are innovated to test? only put `.l` files? (e.g. `add_test` , I could not find in CMakeLists.txt)

**Comment by k-okada** [comment]
https://github.com/euslisp/jskeus/blob/master/.travis.yml#L29

jskeus is not a ros package

--
◉ Kei Okada

**Pull request merged**
