### PR TITLE
Refactoring conditional directives for alternative if statements.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by wmarquesr** [comment]
You can review the PR ?

**Comment by k-okada** [comment]
we understand that EusLisp code has non-standard coding style, but we leave as it is since that code itself has been written before Linux has came out...

**Comment by wmarquesr** [comment]
But do not you agree that this kind of refactoring improves readability and understanding of the code ?

**Comment by furushchev** [comment]
-1

I'm heavily using this program everyday for almost all my projects. So I think we should keep old codes unchanged for stability if there is no significant performance improvement or no error.

**Pull request closed without merging**
