### PR TITLE
[lisp/comp/comp.l] escape c entry

### PR DESCRIPTION
**Pull request by furushchev**
This PR solves issue reported at https://github.com/jsk-ros-pkg/jsk_roseus/pull/464

### CODE REVIEW

**Comment by k-okada** [comment]
did you confirm this outputs same C code except for file contains "-" ?

**Comment by furushchev** [comment]
Except for change in entry by this PR and generated symbol by `gensym`, the code is the same.

```bash
$ roseus
1.irteusgl$ compiler:compile-file-if-src-newer "solve-hanoi.l"
2.irteusgl$ exit
$ ls
solve-hanoi.c  solve-hanoi.h  solve-hanoi.l  solve-hanoi.o  solve-hanoi.so
```

```diff
1,2c1,2
< /* solve-hanoi.c :  entry=solve-hanoi */
< /* compiled by EusLisp 9.19(b6f2306 1.0.12) for Linux64 created on MacBookPro(Mon Aug 8 08:12:13 JST 2016) */
---
> /* solve-hanoi.c :  entry=solve_hanoi */
> /* compiled by EusLisp 9.19(d69cf76 1.0.12) for Linux64 created on MacBookPro(Sun Aug 7 17:55:18 JST 2016) */
5c5
< #pragma init (register_solve-hanoi)
---
> #pragma init (register_solve_hanoi)
11c11
< extern pointer ___solve-hanoi();
---
> extern pointer ___solve_hanoi();
13,14c13,14
< static int register_solve-hanoi()
<   { add_module_initializer("___solve-hanoi", ___solve-hanoi);}
---
> static int register_solve_hanoi()
>   { add_module_initializer("___solve-hanoi", ___solve_hanoi);}
18c18
< pointer ___solve-hanoi(ctx,n,argv,env)
---
> pointer ___solve_hanoi(ctx,n,argv,env)
68,69c68,69
< WHL2140:
< 	if (local[1]==NIL) goto WHX2141;
---
> WHL2150:
> 	if (local[1]==NIL) goto WHX2151;
80,81c80,81
< WHL2145:
< 	if (local[3]==NIL) goto WHX2146;
---
> WHL2155:
> 	if (local[3]==NIL) goto WHX2156;
101,102c101,102
< 	goto WHL2145;
< WHX2146:
---
> 	goto WHL2155;
> WHX2156:
104c104
< BLK2147:
---
> BLK2157:
106,107c106,107
< 	goto WHL2140;
< WHX2141:
---
> 	goto WHL2150;
> WHX2151:
109c109
< BLK2142:
---
> BLK2152:
196c196
< 	if (w==NIL) goto IF2151;
---
> 	if (w==NIL) goto IF2161;
201,202c201,202
< 	goto IF2152;
< IF2151:
---
> 	goto IF2162;
> IF2161:
204c204
< IF2152:
---
> IF2162:
218c218
< 	if (w==NIL) goto IF2153;
---
> 	if (w==NIL) goto IF2163;
222,223c222,223
< 	goto IF2154;
< IF2153:
---
> 	goto IF2164;
> IF2163:
225c225
< IF2154:
---
> IF2164:
```

header file has no diff.

**Comment by furushchev** [comment]
@k-okada I also confirmed that lisp file which loads other lisp files also can be compiled and executed successfully.

```lisp
;; test-1.l
(load "test-2")
(defun f-1 (arg)
   (format t "called f-1 ~A~%" (f-2 arg)))
```

```
;; test-2.l

(defun f-2 (arg)
  (format nil "and f-2 with arg: ~A" arg))
```

```bash
$ irteusgl
$ compiler:compile-file-if-src-newer "test-1.l"
$ exit
# restart irteusgl
$ irteusgl
$ load "test-1"
$ f-1 "aaa"   ;; -> called f-1 and f-2 with arg: aaa
```

**Comment by furushchev** [comment]
@k-okada I also confirmed that lisp file which loads other lisp files also can be compiled and executed successfully.

```lisp
;; test-1.l
(load "test-2")
(defun f-1 (arg)
   (format t "called f-1 ~A~%" (f-2 arg)))
```

```
;; test-2.l

(defun f-2 (arg)
  (format nil "and f-2 with arg: ~A" arg))
```

```bash
$ irteusgl
$ compiler:compile-file-if-src-newer "test-1.l"
$ exit
# restart irteusgl
$ irteusgl
$ load "test-1"
$ f-1 "aaa"   ;; -> called f-1 and f-2 with arg: aaa
```

**Comment by k-okada** [comment]
Cc: @terasawa

**Pull request merged**
