### PR TITLE
support supplied-p for &key / &optional

### PR DESCRIPTION
**Pull request by furushchev**
```lisp
(defun foo (&optional (arg1 1) (arg2 2 arg2-supplied-p))
  (format nil "~A ~A ~A" arg1 arg2 arg2-supplied-p))
;; => foo
(foo)
;; => 1 2 nil
(foo 2)
;; => 2 2 nil
(foo 3 4)
;; => 3 4 t
```

refer: http://www.lispworks.com/documentation/HyperSpec/Body/03_da.htm

Closes  https://github.com/euslisp/EusLisp/issues/240
Related?: https://github.com/euslisp/EusLisp/issues/72

### CODE REVIEW

**Comment by k-okada** [comment]
does anyone knows the test set of common lisp specification?
This change goes to support more common lisp feature in euslisp, and I'd
like to know what other features are missing.

--
◉ Kei Okada


2017-12-01 3:11 GMT+01:00 Affonso, Guilherme <notifications@github.com>:

**Comment by furushchev** [comment]
I found a test suite for common lisp.
https://github.com/Clozure/ccl-tests
Many things are tested there....

**Comment by k-okada** [comment]
nice, so can we make list of supported/non-support features?

--
◉ Kei Okada


2017-12-06 13:34 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by Affonso-Gui** [comment]
@furushchev can we re-target this to `cl-compatible` branch?

**Comment by furushchev** [comment]
@Affonso-Gui Changed
CC: @k-okada

**Comment by k-okada** [comment]
I have added following label related to ci-compatible PR's, to help when we decided to merge these features in to master branch.

ci-compatible/ChangeExistingFeature ;; definitely this breaks current demo program
ci-compatible/AddMissingFeature ;; you can merge into master branch, not problem, may be...
ci-compatible/FixBugs ;; this should be ok, but causes unexpected side effects in most cases...

**Comment by furushchev** [comment]
@k-okada Thanks for the work!

**Pull request merged**
