### PR TITLE
[doc/jlatex/jsysfunc.tex] modify explanation on unix:localtime

### PR DESCRIPTION
**Pull request by kochigami**
I modified ```unix:localtime``` explanation as following every component 
based on https://linux.die.net/man/3/localtime

If there is any problem, please let me know.
```
1.irteusgl$ unix:localtime
#(53   22    14    6     10        116      0            310                                    nil                   ("JST" "JST"))
 sec  min    hour day  month       year   wday    number of days since January 1     is daylight saving time set supporting time zone
```

### CODE REVIEW

**Comment by k-okada** [comment]
nice, please update English docs too, also better add examples you showed on this page.
https://github.com/euslisp/EusLisp/blob/EusLisp-9.21/doc/latex/sysfunc.tex#L231-L233

**Comment by kochigami** [comment]
Thank you very much for your review.
I updated English docs, too.

**Comment by k-okada** [comment]
Please run
```
git fetch --all
git rebase origin/master
```
on this branch

**Comment by kochigami** [comment]
I'm very sorry...I did something wrong. Test failed.

```
git fetch --all
git rebase origin/master
```
Then, I removed merge commit by 
```
git rebase -i HEAD~~ => squashing merging commit 
git push -f kochigami modify-local-time
```
Test started for bout 30 sec, and it failed.
Maybe it was wrong. 
Travis error didn't change.

Current state is 
```
git fetch --all =>
Fetching origin
Fetching kochigami
kochigami@kochigami-ThinkPad-T450:~/catkin_ws/src/EusLisp/doc$ git rebase origin/master 
Current branch modify-unix-localtime is up to date.
```
```
 git log =>
commit f7fd2e2b528329acb4ee65c06b0384eb05c6240b
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Sun Nov 6 14:21:05 2016 +0900

    [system function] modify explanation on unix:localtime

commit 13f04438d458eb1bd1d708a4e0fe333bc7881f71
Merge: 7104835 3b7b768
Author: Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>
Date:   Tue Nov 8 23:36:55 2016 +0900

    Merge pull request #216 from furushchev/osx-hot-fix
    
    [WIP][.travis.sh] add temporal fix for rvm bug on latest travis OSX image
```

**Comment by kochigami** [comment]
すみません、ブラウザを更新したらテストが始まっていました。見間違いでした。

**Pull request merged**
